# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from detect_hog/RobotCamGlobalPos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotCamGlobalPos(genpy.Message):
  _md5sum = "6d936f630f6ff27a9e7df7df229d3501"
  _type = "detect_hog/RobotCamGlobalPos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool left_exist_rob_flag
bool right_exist_rob_flag
bool back_exist_rob_flag
"""
  __slots__ = ['left_exist_rob_flag','right_exist_rob_flag','back_exist_rob_flag']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_exist_rob_flag,right_exist_rob_flag,back_exist_rob_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotCamGlobalPos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_exist_rob_flag is None:
        self.left_exist_rob_flag = False
      if self.right_exist_rob_flag is None:
        self.right_exist_rob_flag = False
      if self.back_exist_rob_flag is None:
        self.back_exist_rob_flag = False
    else:
      self.left_exist_rob_flag = False
      self.right_exist_rob_flag = False
      self.back_exist_rob_flag = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.left_exist_rob_flag, _x.right_exist_rob_flag, _x.back_exist_rob_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.left_exist_rob_flag, _x.right_exist_rob_flag, _x.back_exist_rob_flag,) = _get_struct_3B().unpack(str[start:end])
      self.left_exist_rob_flag = bool(self.left_exist_rob_flag)
      self.right_exist_rob_flag = bool(self.right_exist_rob_flag)
      self.back_exist_rob_flag = bool(self.back_exist_rob_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.left_exist_rob_flag, _x.right_exist_rob_flag, _x.back_exist_rob_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.left_exist_rob_flag, _x.right_exist_rob_flag, _x.back_exist_rob_flag,) = _get_struct_3B().unpack(str[start:end])
      self.left_exist_rob_flag = bool(self.left_exist_rob_flag)
      self.right_exist_rob_flag = bool(self.right_exist_rob_flag)
      self.back_exist_rob_flag = bool(self.back_exist_rob_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
