// Generated by gencpp from file detect_hog/RobotCamGlobalPos.msg
// DO NOT EDIT!


#ifndef DETECT_HOG_MESSAGE_ROBOTCAMGLOBALPOS_H
#define DETECT_HOG_MESSAGE_ROBOTCAMGLOBALPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_hog
{
template <class ContainerAllocator>
struct RobotCamGlobalPos_
{
  typedef RobotCamGlobalPos_<ContainerAllocator> Type;

  RobotCamGlobalPos_()
    : left_exist_rob_flag(false)
    , right_exist_rob_flag(false)
    , back_exist_rob_flag(false)  {
    }
  RobotCamGlobalPos_(const ContainerAllocator& _alloc)
    : left_exist_rob_flag(false)
    , right_exist_rob_flag(false)
    , back_exist_rob_flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _left_exist_rob_flag_type;
  _left_exist_rob_flag_type left_exist_rob_flag;

   typedef uint8_t _right_exist_rob_flag_type;
  _right_exist_rob_flag_type right_exist_rob_flag;

   typedef uint8_t _back_exist_rob_flag_type;
  _back_exist_rob_flag_type back_exist_rob_flag;




  typedef boost::shared_ptr< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> const> ConstPtr;

}; // struct RobotCamGlobalPos_

typedef ::detect_hog::RobotCamGlobalPos_<std::allocator<void> > RobotCamGlobalPos;

typedef boost::shared_ptr< ::detect_hog::RobotCamGlobalPos > RobotCamGlobalPosPtr;
typedef boost::shared_ptr< ::detect_hog::RobotCamGlobalPos const> RobotCamGlobalPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_hog

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'detect_hog': ['/home/nvidia/catkin_tx2/src/detect_hog/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d936f630f6ff27a9e7df7df229d3501";
  }

  static const char* value(const ::detect_hog::RobotCamGlobalPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d936f630f6ff27aULL;
  static const uint64_t static_value2 = 0x9e7df7df229d3501ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_hog/RobotCamGlobalPos";
  }

  static const char* value(const ::detect_hog::RobotCamGlobalPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool left_exist_rob_flag\n\
bool right_exist_rob_flag\n\
bool back_exist_rob_flag\n\
";
  }

  static const char* value(const ::detect_hog::RobotCamGlobalPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_exist_rob_flag);
      stream.next(m.right_exist_rob_flag);
      stream.next(m.back_exist_rob_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotCamGlobalPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_hog::RobotCamGlobalPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_hog::RobotCamGlobalPos_<ContainerAllocator>& v)
  {
    s << indent << "left_exist_rob_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_exist_rob_flag);
    s << indent << "right_exist_rob_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_exist_rob_flag);
    s << indent << "back_exist_rob_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.back_exist_rob_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_HOG_MESSAGE_ROBOTCAMGLOBALPOS_H
